# -*- coding: utf-8 -*-
"""MBongioviCW5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtJ_OObeHxsiqr9GAkEkRyL3AnjeL4DA
"""

import random

a = 30
b = int(input ("How many people might show up?"))
c = random.randint (1,16)

Food = ("Turkey","Apple pie","Mashed potatoes","Mac and cheese")

total = a + b + c

print ("Welcome to my program for Thanksgiving")

answer = "n"

while answer != "y":
  for item in food:
    print ("We need " + str(total) + " " + item)
  answer = input("Do you want to keep going? Type y to exit.")